//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentData
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentDefinition", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public partial class AgentDefinition : object
    {
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string PhoneField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentEntity", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public partial class AgentEntity : object
    {
        
        private int AgentIdField;
        
        private int[] DepartmentIdsField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private bool IsVisibleField;
        
        private string LastNameField;
        
        private string PhoneField;
        
        private string UserIdField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentId
        {
            get
            {
                return this.AgentIdField;
            }
            set
            {
                this.AgentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] DepartmentIds
        {
            get
            {
                return this.DepartmentIdsField;
            }
            set
            {
                this.DepartmentIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVisible
        {
            get
            {
                return this.IsVisibleField;
            }
            set
            {
                this.IsVisibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationRequest", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public partial class AuthenticationRequest : object
    {
        
        private System.Nullable<int> AccessTokenExpAfterSecField;
        
        private string PasswordField;
        
        private System.Nullable<int> RefreshTokenExpAfterSecField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccessTokenExpAfterSec
        {
            get
            {
                return this.AccessTokenExpAfterSecField;
            }
            set
            {
                this.AccessTokenExpAfterSecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RefreshTokenExpAfterSec
        {
            get
            {
                return this.RefreshTokenExpAfterSecField;
            }
            set
            {
                this.RefreshTokenExpAfterSecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResult", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public partial class AuthenticationResult : object
    {
        
        private string AccessTokenField;
        
        private string RefreshTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefreshToken
        {
            get
            {
                return this.RefreshTokenField;
            }
            set
            {
                this.RefreshTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationContext", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public partial class AuthenticationContext : object
    {
        
        private AgentData.AuthenticationRight[] RightsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AgentData.AuthenticationRight[] Rights
        {
            get
            {
                return this.RightsField;
            }
            set
            {
                this.RightsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationRight", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public partial class AuthenticationRight : object
    {
        
        private string FullSysnameField;
        
        private int ModuleIdField;
        
        private int RightIdField;
        
        private string RightSysnameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullSysname
        {
            get
            {
                return this.FullSysnameField;
            }
            set
            {
                this.FullSysnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleId
        {
            get
            {
                return this.ModuleIdField;
            }
            set
            {
                this.ModuleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RightId
        {
            get
            {
                return this.RightIdField;
            }
            set
            {
                this.RightIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RightSysname
        {
            get
            {
                return this.RightSysnameField;
            }
            set
            {
                this.RightSysnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentPasswordChangeResultType", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public enum AgentPasswordChangeResultType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCredentials = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentRight", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public partial class AgentRight : object
    {
        
        private int RightIdField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RightId
        {
            get
            {
                return this.RightIdField;
            }
            set
            {
                this.RightIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleEntity", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public partial class RoleEntity : object
    {
        
        private int IdField;
        
        private int ModuleIdField;
        
        private string NameField;
        
        private string SysnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleId
        {
            get
            {
                return this.ModuleIdField;
            }
            set
            {
                this.ModuleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sysname
        {
            get
            {
                return this.SysnameField;
            }
            set
            {
                this.SysnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericRoleSearchQuery", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AgentData.ByKeywordsRoleSearchQuery))]
    public partial class GenericRoleSearchQuery : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ByKeywordsRoleSearchQuery", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public partial class ByKeywordsRoleSearchQuery : AgentData.GenericRoleSearchQuery
    {
        
        private string[] KeywordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Keywords
        {
            get
            {
                return this.KeywordsField;
            }
            set
            {
                this.KeywordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleSearchEntity", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public partial class RoleSearchEntity : object
    {
        
        private int IdField;
        
        private int ModuleIdField;
        
        private string NameField;
        
        private string SysnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleId
        {
            get
            {
                return this.ModuleIdField;
            }
            set
            {
                this.ModuleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sysname
        {
            get
            {
                return this.SysnameField;
            }
            set
            {
                this.SysnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentSearchQuery", Namespace="http://schemas.datacontract.org/2004/07/BlueBrown.Framework.Agents")]
    public partial class AgentSearchQuery : object
    {
        
        private int[] DepartmentIdsField;
        
        private System.Nullable<bool> IsVisibleField;
        
        private string KeywordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] DepartmentIds
        {
            get
            {
                return this.DepartmentIdsField;
            }
            set
            {
                this.DepartmentIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsVisible
        {
            get
            {
                return this.IsVisibleField;
            }
            set
            {
                this.IsVisibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keyword
        {
            get
            {
                return this.KeywordField;
            }
            set
            {
                this.KeywordField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgentData.IAgentService")]
    public interface IAgentService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/AddRole", ReplyAction="http://tempuri.org/IAgentService/AddRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/AddRoleStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.AddRoleResponse> AddRoleAsync(AgentData.AddRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/AddDepartment", ReplyAction="http://tempuri.org/IAgentService/AddDepartmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/AddDepartmentStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.AddDepartmentResponse> AddDepartmentAsync(AgentData.AddDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/Create", ReplyAction="http://tempuri.org/IAgentService/CreateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/CreateStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.CreateResponse> CreateAsync(AgentData.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/Authenticate", ReplyAction="http://tempuri.org/IAgentService/AuthenticateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/AuthenticateStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.AuthenticateResponse> AuthenticateAsync(AgentData.AuthenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/GetAgentAuthenticationContext", ReplyAction="http://tempuri.org/IAgentService/GetAgentAuthenticationContextResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/GetAgentAuthenticationContextStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.GetAgentAuthenticationContextResponse> GetAgentAuthenticationContextAsync(AgentData.GetAgentAuthenticationContextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/RefreshAccessToken", ReplyAction="http://tempuri.org/IAgentService/RefreshAccessTokenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/RefreshAccessTokenStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.RefreshAccessTokenResponse> RefreshAccessTokenAsync(AgentData.RefreshAccessTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/ChangePassword", ReplyAction="http://tempuri.org/IAgentService/ChangePasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/ChangePasswordStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.ChangePasswordResponse> ChangePasswordAsync(AgentData.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/GetAll", ReplyAction="http://tempuri.org/IAgentService/GetAllResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/GetAllStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.GetAllResponse> GetAllAsync(AgentData.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/Get", ReplyAction="http://tempuri.org/IAgentService/GetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/GetStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.GetResponse> GetAsync(AgentData.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/GetMany", ReplyAction="http://tempuri.org/IAgentService/GetManyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/GetManyStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.GetManyResponse> GetManyAsync(AgentData.GetManyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/GetByAgentId", ReplyAction="http://tempuri.org/IAgentService/GetByAgentIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/GetByAgentIdStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.GetByAgentIdResponse> GetByAgentIdAsync(AgentData.GetByAgentIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/GetByAgentIdMany", ReplyAction="http://tempuri.org/IAgentService/GetByAgentIdManyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/GetByAgentIdManyStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.GetByAgentIdManyResponse> GetByAgentIdManyAsync(AgentData.GetByAgentIdManyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/GetRights", ReplyAction="http://tempuri.org/IAgentService/GetRightsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/GetRightsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.GetRightsResponse> GetRightsAsync(AgentData.GetRightsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/GetRoles", ReplyAction="http://tempuri.org/IAgentService/GetRolesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/GetRolesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.GetRolesResponse> GetRolesAsync(AgentData.GetRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/Remove", ReplyAction="http://tempuri.org/IAgentService/RemoveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/RemoveStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.RemoveResponse> RemoveAsync(AgentData.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/RemoveDepartment", ReplyAction="http://tempuri.org/IAgentService/RemoveDepartmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/RemoveDepartmentStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.RemoveDepartmentResponse> RemoveDepartmentAsync(AgentData.RemoveDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/RemoveRole", ReplyAction="http://tempuri.org/IAgentService/RemoveRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/RemoveRoleStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.RemoveRoleResponse> RemoveRoleAsync(AgentData.RemoveRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/SearchRole", ReplyAction="http://tempuri.org/IAgentService/SearchRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/SearchRoleStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.SearchRoleResponse> SearchRoleAsync(AgentData.SearchRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/ResetPassword", ReplyAction="http://tempuri.org/IAgentService/ResetPasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/ResetPasswordStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.ResetPasswordResponse> ResetPasswordAsync(AgentData.ResetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/SearchAgent", ReplyAction="http://tempuri.org/IAgentService/SearchAgentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/SearchAgentStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.SearchAgentResponse> SearchAgentAsync(AgentData.SearchAgentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/Update", ReplyAction="http://tempuri.org/IAgentService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/UpdateStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.UpdateResponse> UpdateAsync(AgentData.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/UpdateDepartments", ReplyAction="http://tempuri.org/IAgentService/UpdateDepartmentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/UpdateDepartmentsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.UpdateDepartmentsResponse> UpdateDepartmentsAsync(AgentData.UpdateDepartmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/UpdateRights", ReplyAction="http://tempuri.org/IAgentService/UpdateRightsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/UpdateRightsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.UpdateRightsResponse> UpdateRightsAsync(AgentData.UpdateRightsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/UpdateVisibility", ReplyAction="http://tempuri.org/IAgentService/UpdateVisibilityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IAgentService/UpdateVisibilityStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<AgentData.UpdateVisibilityResponse> UpdateVisibilityAsync(AgentData.UpdateVisibilityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddRole", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int roleId;
        
        public AddRoleRequest()
        {
        }
        
        public AddRoleRequest(string userId, int roleId)
        {
            this.userId = userId;
            this.roleId = roleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddRoleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRoleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddRoleResult;
        
        public AddRoleResponse()
        {
        }
        
        public AddRoleResponse(bool AddRoleResult)
        {
            this.AddRoleResult = AddRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDepartment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddDepartmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int departmentId;
        
        public AddDepartmentRequest()
        {
        }
        
        public AddDepartmentRequest(string userId, int departmentId)
        {
            this.userId = userId;
            this.departmentId = departmentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDepartmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddDepartmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddDepartmentResult;
        
        public AddDepartmentResponse()
        {
        }
        
        public AddDepartmentResponse(bool AddDepartmentResult)
        {
            this.AddDepartmentResult = AddDepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentDefinition definition;
        
        public CreateRequest()
        {
        }
        
        public CreateRequest(AgentData.AgentDefinition definition)
        {
            this.definition = definition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentEntity CreateResult;
        
        public CreateResponse()
        {
        }
        
        public CreateResponse(AgentData.AgentEntity CreateResult)
        {
            this.CreateResult = CreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authenticate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AuthenticationRequest request;
        
        public AuthenticateRequest()
        {
        }
        
        public AuthenticateRequest(AgentData.AuthenticationRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AuthenticationResult AuthenticateResult;
        
        public AuthenticateResponse()
        {
        }
        
        public AuthenticateResponse(AgentData.AuthenticationResult AuthenticateResult)
        {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAgentAuthenticationContext", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAgentAuthenticationContextRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public GetAgentAuthenticationContextRequest()
        {
        }
        
        public GetAgentAuthenticationContextRequest(string userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAgentAuthenticationContextResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAgentAuthenticationContextResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AuthenticationContext GetAgentAuthenticationContextResult;
        
        public GetAgentAuthenticationContextResponse()
        {
        }
        
        public GetAgentAuthenticationContextResponse(AgentData.AuthenticationContext GetAgentAuthenticationContextResult)
        {
            this.GetAgentAuthenticationContextResult = GetAgentAuthenticationContextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefreshAccessToken", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RefreshAccessTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string refreshToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Nullable<int> accessTokenExpAfterSec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<int> refreshTokenExpAfterSec;
        
        public RefreshAccessTokenRequest()
        {
        }
        
        public RefreshAccessTokenRequest(string refreshToken, System.Nullable<int> accessTokenExpAfterSec, System.Nullable<int> refreshTokenExpAfterSec)
        {
            this.refreshToken = refreshToken;
            this.accessTokenExpAfterSec = accessTokenExpAfterSec;
            this.refreshTokenExpAfterSec = refreshTokenExpAfterSec;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefreshAccessTokenResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RefreshAccessTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AuthenticationResult RefreshAccessTokenResult;
        
        public RefreshAccessTokenResponse()
        {
        }
        
        public RefreshAccessTokenResponse(AgentData.AuthenticationResult RefreshAccessTokenResult)
        {
            this.RefreshAccessTokenResult = RefreshAccessTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangePasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string currentPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string newPassword;
        
        public ChangePasswordRequest()
        {
        }
        
        public ChangePasswordRequest(string userId, string currentPassword, string newPassword)
        {
            this.userId = userId;
            this.currentPassword = currentPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangePasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentPasswordChangeResultType ChangePasswordResult;
        
        public ChangePasswordResponse()
        {
        }
        
        public ChangePasswordResponse(AgentData.AgentPasswordChangeResultType ChangePasswordResult)
        {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAll", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllRequest
    {
        
        public GetAllRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentEntity[] GetAllResult;
        
        public GetAllResponse()
        {
        }
        
        public GetAllResponse(AgentData.AgentEntity[] GetAllResult)
        {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public GetRequest()
        {
        }
        
        public GetRequest(string userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentEntity GetResult;
        
        public GetResponse()
        {
        }
        
        public GetResponse(AgentData.AgentEntity GetResult)
        {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMany", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetManyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] userIds;
        
        public GetManyRequest()
        {
        }
        
        public GetManyRequest(string[] userIds)
        {
            this.userIds = userIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetManyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetManyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentEntity[] GetManyResult;
        
        public GetManyResponse()
        {
        }
        
        public GetManyResponse(AgentData.AgentEntity[] GetManyResult)
        {
            this.GetManyResult = GetManyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetByAgentId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetByAgentIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int agentId;
        
        public GetByAgentIdRequest()
        {
        }
        
        public GetByAgentIdRequest(int agentId)
        {
            this.agentId = agentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetByAgentIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetByAgentIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentEntity GetByAgentIdResult;
        
        public GetByAgentIdResponse()
        {
        }
        
        public GetByAgentIdResponse(AgentData.AgentEntity GetByAgentIdResult)
        {
            this.GetByAgentIdResult = GetByAgentIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetByAgentIdMany", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetByAgentIdManyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] agentIds;
        
        public GetByAgentIdManyRequest()
        {
        }
        
        public GetByAgentIdManyRequest(int[] agentIds)
        {
            this.agentIds = agentIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetByAgentIdManyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetByAgentIdManyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentEntity[] GetByAgentIdManyResult;
        
        public GetByAgentIdManyResponse()
        {
        }
        
        public GetByAgentIdManyResponse(AgentData.AgentEntity[] GetByAgentIdManyResult)
        {
            this.GetByAgentIdManyResult = GetByAgentIdManyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRights", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRightsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public GetRightsRequest()
        {
        }
        
        public GetRightsRequest(string userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRightsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRightsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentRight[] GetRightsResult;
        
        public GetRightsResponse()
        {
        }
        
        public GetRightsResponse(AgentData.AgentRight[] GetRightsResult)
        {
            this.GetRightsResult = GetRightsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRoles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRolesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public GetRolesRequest()
        {
        }
        
        public GetRolesRequest(string userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRolesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRolesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.RoleEntity[] GetRolesResult;
        
        public GetRolesResponse()
        {
        }
        
        public GetRolesResponse(AgentData.RoleEntity[] GetRolesResult)
        {
            this.GetRolesResult = GetRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Remove", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public RemoveRequest()
        {
        }
        
        public RemoveRequest(string userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveResponse
    {
        
        public RemoveResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveDepartment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveDepartmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int departmentId;
        
        public RemoveDepartmentRequest()
        {
        }
        
        public RemoveDepartmentRequest(string userId, int departmentId)
        {
            this.userId = userId;
            this.departmentId = departmentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveDepartmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveDepartmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RemoveDepartmentResult;
        
        public RemoveDepartmentResponse()
        {
        }
        
        public RemoveDepartmentResponse(bool RemoveDepartmentResult)
        {
            this.RemoveDepartmentResult = RemoveDepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveRole", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int roleId;
        
        public RemoveRoleRequest()
        {
        }
        
        public RemoveRoleRequest(string userId, int roleId)
        {
            this.userId = userId;
            this.roleId = roleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveRoleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveRoleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RemoveRoleResult;
        
        public RemoveRoleResponse()
        {
        }
        
        public RemoveRoleResponse(bool RemoveRoleResult)
        {
            this.RemoveRoleResult = RemoveRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchRole", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.GenericRoleSearchQuery query;
        
        public SearchRoleRequest()
        {
        }
        
        public SearchRoleRequest(AgentData.GenericRoleSearchQuery query)
        {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchRoleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchRoleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.RoleSearchEntity[] SearchRoleResult;
        
        public SearchRoleResponse()
        {
        }
        
        public SearchRoleResponse(AgentData.RoleSearchEntity[] SearchRoleResult)
        {
            this.SearchRoleResult = SearchRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetPassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResetPasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public ResetPasswordRequest()
        {
        }
        
        public ResetPasswordRequest(string userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetPasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResetPasswordResponse
    {
        
        public ResetPasswordResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchAgent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchAgentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentSearchQuery userId;
        
        public SearchAgentRequest()
        {
        }
        
        public SearchAgentRequest(AgentData.AgentSearchQuery userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchAgentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchAgentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentEntity[] SearchAgentResult;
        
        public SearchAgentResponse()
        {
        }
        
        public SearchAgentResponse(AgentData.AgentEntity[] SearchAgentResult)
        {
            this.SearchAgentResult = SearchAgentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public AgentData.AgentDefinition definition;
        
        public UpdateRequest()
        {
        }
        
        public UpdateRequest(string userId, AgentData.AgentDefinition definition)
        {
            this.userId = userId;
            this.definition = definition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AgentData.AgentEntity UpdateResult;
        
        public UpdateResponse()
        {
        }
        
        public UpdateResponse(AgentData.AgentEntity UpdateResult)
        {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDepartments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateDepartmentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int[] departments;
        
        public UpdateDepartmentsRequest()
        {
        }
        
        public UpdateDepartmentsRequest(string userId, int[] departments)
        {
            this.userId = userId;
            this.departments = departments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDepartmentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateDepartmentsResponse
    {
        
        public UpdateDepartmentsResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRights", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRightsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public AgentData.AgentRight[] rights;
        
        public UpdateRightsRequest()
        {
        }
        
        public UpdateRightsRequest(string userId, AgentData.AgentRight[] rights)
        {
            this.userId = userId;
            this.rights = rights;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRightsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRightsResponse
    {
        
        public UpdateRightsResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateVisibility", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateVisibilityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool isVisible;
        
        public UpdateVisibilityRequest()
        {
        }
        
        public UpdateVisibilityRequest(string userId, bool isVisible)
        {
            this.userId = userId;
            this.isVisible = isVisible;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateVisibilityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateVisibilityResponse
    {
        
        public UpdateVisibilityResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IAgentServiceChannel : AgentData.IAgentService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class AgentServiceClient : System.ServiceModel.ClientBase<AgentData.IAgentService>, AgentData.IAgentService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AgentServiceClient() : 
                base(AgentServiceClient.GetDefaultBinding(), AgentServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomBinding_IAgentService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgentServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AgentServiceClient.GetBindingForEndpoint(endpointConfiguration), AgentServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgentServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AgentServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgentServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AgentServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AgentData.AddRoleResponse> AddRoleAsync(AgentData.AddRoleRequest request)
        {
            return base.Channel.AddRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.AddDepartmentResponse> AddDepartmentAsync(AgentData.AddDepartmentRequest request)
        {
            return base.Channel.AddDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.CreateResponse> CreateAsync(AgentData.CreateRequest request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.AuthenticateResponse> AuthenticateAsync(AgentData.AuthenticateRequest request)
        {
            return base.Channel.AuthenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.GetAgentAuthenticationContextResponse> GetAgentAuthenticationContextAsync(AgentData.GetAgentAuthenticationContextRequest request)
        {
            return base.Channel.GetAgentAuthenticationContextAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.RefreshAccessTokenResponse> RefreshAccessTokenAsync(AgentData.RefreshAccessTokenRequest request)
        {
            return base.Channel.RefreshAccessTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.ChangePasswordResponse> ChangePasswordAsync(AgentData.ChangePasswordRequest request)
        {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.GetAllResponse> GetAllAsync(AgentData.GetAllRequest request)
        {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.GetResponse> GetAsync(AgentData.GetRequest request)
        {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.GetManyResponse> GetManyAsync(AgentData.GetManyRequest request)
        {
            return base.Channel.GetManyAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.GetByAgentIdResponse> GetByAgentIdAsync(AgentData.GetByAgentIdRequest request)
        {
            return base.Channel.GetByAgentIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.GetByAgentIdManyResponse> GetByAgentIdManyAsync(AgentData.GetByAgentIdManyRequest request)
        {
            return base.Channel.GetByAgentIdManyAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.GetRightsResponse> GetRightsAsync(AgentData.GetRightsRequest request)
        {
            return base.Channel.GetRightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.GetRolesResponse> GetRolesAsync(AgentData.GetRolesRequest request)
        {
            return base.Channel.GetRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.RemoveResponse> RemoveAsync(AgentData.RemoveRequest request)
        {
            return base.Channel.RemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.RemoveDepartmentResponse> RemoveDepartmentAsync(AgentData.RemoveDepartmentRequest request)
        {
            return base.Channel.RemoveDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.RemoveRoleResponse> RemoveRoleAsync(AgentData.RemoveRoleRequest request)
        {
            return base.Channel.RemoveRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.SearchRoleResponse> SearchRoleAsync(AgentData.SearchRoleRequest request)
        {
            return base.Channel.SearchRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.ResetPasswordResponse> ResetPasswordAsync(AgentData.ResetPasswordRequest request)
        {
            return base.Channel.ResetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.SearchAgentResponse> SearchAgentAsync(AgentData.SearchAgentRequest request)
        {
            return base.Channel.SearchAgentAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.UpdateResponse> UpdateAsync(AgentData.UpdateRequest request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.UpdateDepartmentsResponse> UpdateDepartmentsAsync(AgentData.UpdateDepartmentsRequest request)
        {
            return base.Channel.UpdateDepartmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.UpdateRightsResponse> UpdateRightsAsync(AgentData.UpdateRightsRequest request)
        {
            return base.Channel.UpdateRightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentData.UpdateVisibilityResponse> UpdateVisibilityAsync(AgentData.UpdateVisibilityRequest request)
        {
            return base.Channel.UpdateVisibilityAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IAgentService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                result.Elements.Add(new System.ServiceModel.Channels.BinaryMessageEncodingBindingElement());
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IAgentService))
            {
                return new System.ServiceModel.EndpointAddress(new System.Uri("http://services-agents.devgr-novibet.systems/Agent.svc"), new System.ServiceModel.DnsEndpointIdentity("localhost"));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AgentServiceClient.GetBindingForEndpoint(EndpointConfiguration.CustomBinding_IAgentService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AgentServiceClient.GetEndpointAddress(EndpointConfiguration.CustomBinding_IAgentService);
        }
        
        public enum EndpointConfiguration
        {
            
            CustomBinding_IAgentService,
        }
    }
}
